In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt 
import seaborn as sb
from pathlib import Path
import pytest

In [ ]:
PATH_ROOT  = Path.cwd().parent.parent
print(PATH_ROOT)
DATASET_ROOT = PATH_ROOT /"Sales.csv"
DATASET=pd.read_csv(DATASET_ROOT)
DATASET.head()

c:\Users\IGO\OneDrive\Bureau\DA PROJECTS\PROJECT  bike sales analysis

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,26/11/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,26/11/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,23/03/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,23/03/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,15/05/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [ ]:
DATASET.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [ ]:
import pandas as pd
#from utils.logs import section,logger
from pathlib import Path
import time


# ════════════════════════════════════════════════════════════
# STEP 1 — VALIDATE FILE EXISTS
# ════════════════════════════════════════════════════════════

def validate_file(file_path: str) -> Path:
    #section("STEP 1 — FILE VALIDATION")
    path = Path(file_path).resolve()

    # Check existence
    if not path.exists():
        #logger.error(f"File not found: {path}")
        raise FileNotFoundError(f" File not found: {path}")
    #logger.info(f" File found      : {path.name}")

    # Check extension
    if path.suffix.lower() != ".csv":
        raise ValueError(f" Expected a .csv file, got: '{path.suffix}'")
    #logger.info(f" File extension  : {path.suffix}")


    # Check file size
    size_kb = path.stat().st_size / 1024
    size_mb = size_kb / 1024
    #logger.info(f" File size       : {size_mb:.2f} MB ({size_kb:,.1f} KB)")
    if path.stat().st_size == 0:
        raise ValueError(" File is empty (0 bytes).")

    #logger.info(f" Full path       : {path}")

    return path

    


p=validate_file(DATASET_ROOT)
print(p)

C:\Users\IGO\OneDrive\Bureau\DA PROJECTS\PROJECT  bike sales analysis\Sales.csv

In [ ]:


path = Path(DATASET_ROOT).resolve()
print(path)
path.exists()==True

C:\Users\IGO\OneDrive\Bureau\DA PROJECTS\PROJECT  bike sales analysis\Sales.csv

True

In [ ]:
missing_count = DATASET.isnull().sum()


print(missing_count)

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

In [ ]:
n_dupes = DATASET.duplicated().sum()
print(f"Number of duplicate rows: {n_dupes}")

n_col = DATASET.columns.duplicated().sum()
print(f"Number of duplicate columns: {n_col}")

len(DATASET.columns)

Number of duplicate rows: 1000
Number of duplicate columns: 0

18

In [ ]:

num_df = DATASET.select_dtypes(include="number")
summary = num_df.describe().T
summary["range"]    = summary["max"] - summary["min"]
summary["cv%"]      = (summary["std"] / summary["mean"] * 100).round(2)  # Coefficient of variation
print(summary.round(2).to_string())

                   count     mean      std     min     25%     50%     75%      max    range     cv%
Day             113036.0    15.67     8.78     1.0     8.0    16.0    23.0     31.0     30.0   56.06
Year            113036.0  2014.40     1.27  2011.0  2013.0  2014.0  2016.0   2016.0      5.0    0.06
Customer_Age    113036.0    35.92    11.02    17.0    28.0    35.0    43.0     87.0     70.0   30.69
Order_Quantity  113036.0    11.90     9.56     1.0     2.0    10.0    20.0     32.0     31.0   80.34
Unit_Cost       113036.0   267.30   549.84     1.0     2.0     9.0    42.0   2171.0   2170.0  205.70
Unit_Price      113036.0   452.94   922.07     2.0     5.0    24.0    70.0   3578.0   3576.0  203.58
Profit          113036.0   285.05   453.89   -30.0    29.0   101.0   358.0  15096.0  15126.0  159.23
Cost            113036.0   469.32   884.87     1.0    28.0   108.0   432.0  42978.0  42977.0  188.54
Revenue         113036.0   754.37  1309.09     2.0    63.0   223.0   800.0  58074.0  58072.0  173.53

In [ ]:
DATASET["Age_Group"].unique()

array(['Youth (<25)', 'Adults (35-64)', 'Young Adults (25-34)',
       'Seniors (64+)'], dtype=object)

In [ ]:
DATASET.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,26/11/2013,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,26/11/2015,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,23/03/2014,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,23/03/2016,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,15/05/2014,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [ ]:
f=DATASET["Sub_Category"].unique()
c=DATASET["Sub_Category"].nunique()

print(f,c)

['Bike Racks' 'Bike Stands' 'Bottles and Cages' 'Caps' 'Cleaners'
 'Fenders' 'Gloves' 'Helmets' 'Hydration Packs' 'Jerseys' 'Mountain Bikes'
 'Road Bikes' 'Shorts' 'Socks' 'Tires and Tubes' 'Touring Bikes' 'Vests'] 17

In [ ]:
DATASET.shape

(113036, 18)

In [ ]:
DATASET.describe(include="all")

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036,113036.000000,113036,113036.000000,113036.000000,113036,113036,113036,113036,113036,113036,113036,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
unique,1884,NaN,12,NaN,NaN,4,2,6,53,3,17,130,NaN,NaN,NaN,NaN,NaN,NaN
top,01/03/2014,NaN,June,NaN,NaN,Adults (35-64),M,United States,California,Accessories,Tires and Tubes,Water Bottle - 30 oz.,NaN,NaN,NaN,NaN,NaN,NaN
freq,288,NaN,11234,NaN,NaN,55824,58312,39206,22450,70120,33870,10794,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,15.665753,NaN,2014.401739,35.919212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,NaN,8.781567,NaN,1.272510,11.021936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,NaN,1.000000,NaN,2011.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,NaN,8.000000,NaN,2013.000000,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,NaN,16.000000,NaN,2014.000000,35.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,NaN,23.000000,NaN,2016.000000,43.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,NaN,31.000000,NaN,2016.000000,87.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000